# Generated by Django 5.2.3 on 2025-07-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_battery_cycle_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycledata",
            name="avg_current",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="cycledata",
            name="avg_voltage",
            field=models.FloatField(null=True),
        ),
    ]
