# Generated by Django 5.2.3 on 2025-07-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cycledata_avg_current_cycledata_avg_voltage"),
    ]

    operations = [
        migrations.AddField(
            model_name="battery",
            name="c_rate",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="stress_test",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
