# Generated by Django 5.2.3 on 2025-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_battery_c_rate_battery_stress_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="battery",
            name="balanced_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="durability_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="overall_avg_discharge",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="overall_avg_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="resilience_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battery",
            name="state_of_health",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
